services:
  web:
    build: .
    ports: 
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DJANGO_SECRET_KEY=django-insecure-+a#q(hvbq0pf7hlt4uvw%ot=e9m2xf5u+bwo(5m^3q-vsf!rix
      - DJANGO_DEBUG=True

  db:
    image: postgres:15
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
    - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
