FROM python:3.12-bullseye

ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

RUN python -m pip install --upgrade pip

# install dependencies first (for better cache)
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# then copy the rest of the project
COPY . .